
asd_wordbank_set = {
    'asd',
    'asd disorder',
    'asd spectrum',
    'asperger',
    'aspergers',
    'aspergers autism',
    'autism',
    'autism disorder',
    'autism spectrum',
    'autism spectrum disorder',
    'autistic',
    'autistic spectrum disorder',
    'autistic spectrum disorders',
    'high functioning autism',
    'high-functioning autism spectrum disorder',
    'neurodivergent'
}

aba_wordbank_set = {
    'aba',
    'aba behavior',
    'aba behavior therapy',
    'aba behavioral therapy',
    'aba conversion therapy',
    'aba home therapy',
    'aba school',
    'aba services',
    'aba therapist',
    'aba therapy',
    'aba therapy center',
    'aba therapy school',
    'aba therapy services',
    'aba training',
    'aba tutor',
    'acceptance and commitment therapy',
    'applied behavior analysis',
    'applied behaviour analysis',
    'bcaba',
    'bcba',
    'behavior',
    'behavior analysis',
    'behavior analyst',
    'behavior technician',
    'behavior therapy',
    'behavioral analysis',
    'behavioral therapy',
    'behaviorism',
    'behaviour',
    'behaviour analysis',
    'behaviour technician',
    'behavioural analysis',
    'discrete trial training',
    'dtt',
    'rbt',
    'registered behavior technician',
    'registered behaviour technician'
}